/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ec.edu.ups.vista;

import ec.edu.ups.controlador.ControladorTicket;
import java.util.Locale;
import java.util.ResourceBundle;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author tano
 */
public class VentanaListarTickets extends javax.swing.JInternalFrame {
    
    private ControladorTicket controladorTicket;
    
    public VentanaListarTickets(ControladorTicket controladorTicket) {
	initComponents();
	this.controladorTicket = controladorTicket;
	this.controladorTicket.listarTickets((DefaultTableModel) jTable1.getModel());
    }
    
    public void actualizar(){
	this.controladorTicket.listarTickets((DefaultTableModel) jTable1.getModel());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setClosable(true);
        setMaximizable(true);
        setResizable(true);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Codigo", "Ingreso", "Salida", "Total", "Cedula", "Nombre", "Direccion", "Telefono", "Placa", "Marca", "Modelo"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Short.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 766, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 555, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables

    void cambiarIdioma(Locale localizacion, ResourceBundle mensajes) {
	jTable1.getColumnModel().getColumn(0).setHeaderValue(mensajes.getString("ticketsCodigo"));
	jTable1.getColumnModel().getColumn(1).setHeaderValue(mensajes.getString("listaIngreso"));
	jTable1.getColumnModel().getColumn(2).setHeaderValue(mensajes.getString("listaISalida"));
	jTable1.getColumnModel().getColumn(3).setHeaderValue(mensajes.getString("listaTotal"));
	jTable1.getColumnModel().getColumn(4).setHeaderValue(mensajes.getString("clientesCédula"));
	jTable1.getColumnModel().getColumn(5).setHeaderValue(mensajes.getString("clientesNombre"));
	jTable1.getColumnModel().getColumn(6).setHeaderValue(mensajes.getString("clientesDirección"));
	jTable1.getColumnModel().getColumn(7).setHeaderValue(mensajes.getString("clientesTeléfono"));
	jTable1.getColumnModel().getColumn(8).setHeaderValue(mensajes.getString("vehiculosPlaca"));
	jTable1.getColumnModel().getColumn(9).setHeaderValue(mensajes.getString("vehiculosMarca"));
	jTable1.getColumnModel().getColumn(10).setHeaderValue(mensajes.getString("vehiculosModelo"));
    }
}
